sudo: required
dist: trusty
language: node_js
python:
  - "3.5"
  - "3.6"
node_js:
  - "7.10"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
before_install:
  - sudo apt-get -y install python3-pip python-dev
# command to install dependencies
install:
  - "npm --prefix ./gui install ./gui"
  - "pip3 install -r requirements.txt"
# command to run tests
script: 
  - find . -iname "*.py" | xargs pylint --reports=n
  - npm --prefix ./gui run test
